### ISSUE TITLE
Support snap parallel installs

### ISSUE THREAD

**Issue by lengau** [canonical/craft-application#411] opened 2024-08-12 14:44 UTC
### What needs to get done

If the application is installed as a snap, we need to be able to copy that same parallel install's revision into the provider rather than the default (un-instanced) revision.

### Why it needs to get done

https://github.com/canonical/charmcraft/issues/1770

**Comment by dilyn-corner** [comment] 2024-08-30 16:57
I mentioned a trivially reproducible case in the snapcraft matrix room, but I will cross-post it here for easy reference:

```
git clone -b split_kernel_initrd_plugins --depth 1 https://github.com/kubiko/snapcraft
cd snapcraft

snapcraft
snap install --dangerous --classic snapcraft_8*.snap snapcraft_kernel

cd ../

git clone -b 24-riscv64-nezha --depth 1 https://github.com/canonical/iot-field-kernel-snap
cd iot-field-kernel-snap
snapcraft_kernel
```

Error message you will receive:
```
Bad snapcraft.yaml content:
- plugin not registered: 'initrd' (in field 'parts.initrd')  
```

`snapcraft_kernel` is precisely the version of snapcraft which supports the initrd plugin -- the snapcraft installed as `snapcraft` is actually the one being injected into the build environment.

**Comment by mr-cal** [comment] 2024-09-16 15:46
Closing because this piece in craft-application is fixed, but we will likely run into the next issue in craft-providers.

The craft-providers fix is probably changing [this line](https://github.com/canonical/craft-providers/blob/262978901d49e5c16668d8f0bc251b185837cee9/craft_providers/actions/snap_installer.py#L262) to snap_name.split('_')[0].

**Closed by mr-cal** 2024-09-16 15:46 UTC
Labels: Enhancement, triaged
