### ISSUE TITLE
Handle multiple project filenames and assert dirs

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#179] opened 2024-01-26 16:55 UTC
### What needs to get done

- find `snapcraft.yaml` that can exist in `.`, `snap/`, etc
    - these are relative to (and inside) the project path
    - raise an error if multiple project files exist - check with @sergiusens if this should be an error or warning
- asset directory should be a member of the SnapcraftApplication class

### Why it needs to get done

To support snapcraft rebasing onto craft-application.

**Comment by lengau** [comment] 2024-01-31 20:00
Looks like this is a partial duplicate of #148. `SnapcraftApplication` just needs to override `_resolve_project_path` to do the appropriate detection, and it can fail however it chooses.

Likewise the asset directory can be added to `SnapcraftApplication` but isn't relevant for craft-application

**Closed by lengau** 2024-01-31 20:00 UTC
